# Generated by Django 4.2.7 on 2023-12-06 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='shipping_type',
            field=models.CharField(choices=[('N', 'Normal'), ('E', 'Express')], default='N', max_length=1),
        ),
    ]
