# Generated by Django 4.2.7 on 2023-11-27 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='stripe',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
