# Generated by Django 4.2.7 on 2023-12-03 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_claim'),
    ]

    operations = [
        migrations.AddField(
            model_name='claim',
            name='state',
            field=models.CharField(choices=[('Pending', 'Pendiente de revisión'), ('In Process', 'En proceso'), ('Resolved', 'Resuelta'), ('Closed', 'Cerrada')], default='Pending', max_length=20),
        ),
    ]
