# Generated by Django 4.2.7 on 2023-12-01 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_alter_order_user'),
        ('store', '0002_order_stripe'),
    ]

    operations = [
    ]
