services:

  web:
    build: .
    working_dir: /routejet
    command: celery -A routejet worker --beat && python manage.py runserver 0.0.0.0:8000
    restart: always
    volumes:
      - .:/routejet
    ports: 
      - "8000:8000"
    environment:
      - CELERY_BROKER_URL=redis://redis:6379
    depends_on:
      - redis

  redis:
    image: redis:7.0.4
    restart: always
    volumes:
      - ./data/redis:/data