services:

  web:
    build: .
    command: sh launch.sh
    restart: always
    volumes:
      - .:/app
    expose:
      - "5000"
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_BACKEND_URL=redis://redis:6379/0
      - DJANGO_SUPERUSER_EMAIL=admin@gmail.com
      - DJANGO_SUPERUSER_USERNAME=admin
      - DJANGO_SUPERUSER_PASSWORD=admin
      - DJANGO_SETTINGS_MODULE=routejet.settings.local
      - DEBUG=False
    depends_on:
      - redis 
  
  celery:
    build: .
    working_dir: /app/routejet
    command: celery -A routejet worker --beat
    restart: always
    volumes:
      - .:/app
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_BACKEND_URL=redis://redis:6379/0
      - DJANGO_SETTINGS_MODULE=routejet.settings.local
      - DEBUG=False
    depends_on:
      - redis
  
  redis:
    image: redis:7.0.4
    restart: always
    volumes:
      - ./data/redis:/data

  nginx:
    image: nginx:1.23.1
    restart: always
    volumes:
      - ./config/nginx:/etc/nginx/templates
      - .:/app
    ports:
      - "80:80"
    depends_on:
      - web