# Generated by Django 4.2.7 on 2023-11-23 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image', models.ImageField(blank=True, upload_to='product_images')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('available', models.BooleanField(default=True)),
                ('num_products', models.IntegerField(default=100)),
                ('slug', models.SlugField(default='default-slug')),
            ],
        ),
    ]
