# Generated by Django 4.2.7 on 2023-11-28 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='num_products',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
