# Generated by Django 4.2.7 on 2023-12-03 16:43

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('product', '0003_valoracion'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Valoracion',
            new_name='Review',
        ),
    ]
