# Generated by Django 4.2.7 on 2023-11-23 00:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_remove_product_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('country', 'city', 'start_date', 'end_date')},
        ),
    ]
