# Generated by Django 4.2.7 on 2023-11-23 14:52

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0004_alter_product_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="product",
            options={},
        ),
    ]
