# Generated by Django 4.2.7 on 2023-12-03 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_rename_valoracion_review'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='date',
        ),
        migrations.AlterField(
            model_name='review',
            name='description',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='review',
            name='valoration',
            field=models.IntegerField(),
        ),
    ]
