# Generated by Django 4.2.7 on 2023-11-23 15:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_alter_product_options_product_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='end_date',
            field=models.DateField(validators=[django.core.validators.MinValueValidator(limit_value=models.F('start_date'), message='La fecha de fin no puede ser anterior a la fecha de inicio.')]),
        ),
        migrations.AlterField(
            model_name='product',
            name='num_products',
            field=models.IntegerField(default=100, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
    ]
