# Generated by Django 4.2.7 on 2023-11-26 20:04

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0005_alter_product_options"),
        ("product", "0007_alter_product_options_alter_product_end_date_and_more"),
    ]

    operations = []
