# Generated by Django 4.2.7 on 2023-11-25 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_alter_product_slug'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='product',
            name='product_pro_id_b9e5a0_idx',
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(auto_created=True, max_length=100, unique=True),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['id'], name='product_pro_id_06b227_idx'),
        ),
    ]
