# Generated by Django 4.2.7 on 2023-11-26 20:04

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0008_merge_20231126_2004"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="product",
            options={"ordering": ["country", "city", "start_date"]},
        ),
    ]
